spring.application.name=carehub-api
spring.datasource.url=jdbc:postgresql://localhost:5432/CareHub
spring.datasource.username=postgres
spring.datasource.password=KRISH@123CS
server.port=8081
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true